# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
defaults: &defaults
  docker: 
      -  image: amazon/aws-cli
commands:
  to_checkout:
    description: "to checkout the code"
    steps:
      -  checkout
  destroy_environment: 
    steps:
      - run:
          name: Rollback network resources
          command: |
            aws cloudformation delete-stack --stack-name prod-${CIRCLE_WORKFLOW_ID}
          when: on_fail
jobs:
  build:
    <<: *defaults
    steps:
      -  to_checkout
      -  run: npm i
      -  run: npm run lint
  test:
     <<: *defaults
     steps:
      -  to_checkout
      -  run: npm i
      -  run: npm run test
  analyse:
     <<: *defaults
     steps:
      -  to_checkout
      -  run: npm audit
      -  run:
           command: echo "job failed"
           when: on_fail

workflows:
  my_workflow:
    jobs:
     -  build
     -  test:
           requires:
             -  build
     -  analyse:
           requires:
             -  test